// <auto-generated />
using System;
using HelmesWebAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HelmesWebAPI.Migrations
{
    [DbContext(typeof(HelmesContext))]
    [Migration("20220715115627_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Helmes.Entities.Sector", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Pid")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Sector");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Manufacturing",
                            Name = "Manufacturing"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Construction materials",
                            Name = "Construction materials",
                            Pid = 1
                        },
                        new
                        {
                            ID = 3,
                            Description = "Electronics and Optics",
                            Name = "Electronics and Optics",
                            Pid = 1
                        },
                        new
                        {
                            ID = 4,
                            Description = "Food and Beverage",
                            Name = "Food and Beverage",
                            Pid = 1
                        },
                        new
                        {
                            ID = 5,
                            Description = "Bakery &amp; confectionery products",
                            Name = "Bakery &amp; confectionery products",
                            Pid = 4
                        },
                        new
                        {
                            ID = 6,
                            Description = "Beverages",
                            Name = "Beverages",
                            Pid = 4
                        },
                        new
                        {
                            ID = 7,
                            Description = "Fish &amp; fish products",
                            Name = "Fish &amp; fish products",
                            Pid = 4
                        },
                        new
                        {
                            ID = 8,
                            Description = "Meat &amp; meat products",
                            Name = "Meat &amp; meat products",
                            Pid = 4
                        },
                        new
                        {
                            ID = 9,
                            Description = "Milk &amp; dairy products",
                            Name = "Milk &amp; dairy products",
                            Pid = 4
                        },
                        new
                        {
                            ID = 10,
                            Description = "Other",
                            Name = "Other",
                            Pid = 4
                        },
                        new
                        {
                            ID = 11,
                            Description = "Sweets &amp; snack food",
                            Name = "Sweets &amp; snack food",
                            Pid = 4
                        },
                        new
                        {
                            ID = 12,
                            Description = "Furniture",
                            Name = "Furniture",
                            Pid = 1
                        },
                        new
                        {
                            ID = 13,
                            Description = "Bathroom/sauna",
                            Name = "Bathroom/sauna",
                            Pid = 12
                        },
                        new
                        {
                            ID = 14,
                            Description = "Bedroom",
                            Name = "Bedroom",
                            Pid = 12
                        },
                        new
                        {
                            ID = 15,
                            Description = "Children’s room",
                            Name = "Children’s room",
                            Pid = 12
                        },
                        new
                        {
                            ID = 16,
                            Description = "Kitchen",
                            Name = "Kitchen",
                            Pid = 12
                        },
                        new
                        {
                            ID = 17,
                            Description = "Living room",
                            Name = "Living room",
                            Pid = 12
                        },
                        new
                        {
                            ID = 18,
                            Description = "Office",
                            Name = "Office",
                            Pid = 12
                        },
                        new
                        {
                            ID = 19,
                            Description = "Other (Furniture)",
                            Name = "Other (Furniture)",
                            Pid = 12
                        },
                        new
                        {
                            ID = 20,
                            Description = "Outdoor",
                            Name = "Outdoor",
                            Pid = 12
                        },
                        new
                        {
                            ID = 21,
                            Description = "Project furniture",
                            Name = "Project furniture",
                            Pid = 12
                        },
                        new
                        {
                            ID = 22,
                            Description = "Machinery",
                            Name = "Machinery",
                            Pid = 1
                        },
                        new
                        {
                            ID = 23,
                            Description = "Machinery components",
                            Name = "Machinery components",
                            Pid = 22
                        },
                        new
                        {
                            ID = 24,
                            Description = "Machinery equipment/tools",
                            Name = "Machinery equipment/tools",
                            Pid = 22
                        },
                        new
                        {
                            ID = 25,
                            Description = "Manufacture of machinery",
                            Name = "Manufacture of machinery",
                            Pid = 22
                        },
                        new
                        {
                            ID = 26,
                            Description = "Maritime",
                            Name = "Maritime",
                            Pid = 22
                        },
                        new
                        {
                            ID = 27,
                            Description = "Aluminium and steel workboats",
                            Name = "Aluminium and steel workboats",
                            Pid = 26
                        },
                        new
                        {
                            ID = 28,
                            Description = "Boat/Yacht building",
                            Name = "Boat/Yacht building",
                            Pid = 26
                        },
                        new
                        {
                            ID = 29,
                            Description = "Ship repair and conversion",
                            Name = "Ship repair and conversion",
                            Pid = 26
                        },
                        new
                        {
                            ID = 30,
                            Description = "Metal structures",
                            Name = "Metal structures",
                            Pid = 22
                        },
                        new
                        {
                            ID = 31,
                            Description = "Other",
                            Name = "Other",
                            Pid = 22
                        },
                        new
                        {
                            ID = 32,
                            Description = "Repair and maintenance service",
                            Name = "Repair and maintenance service",
                            Pid = 22
                        },
                        new
                        {
                            ID = 33,
                            Description = "Metalworking",
                            Name = "Metalworking",
                            Pid = 1
                        },
                        new
                        {
                            ID = 34,
                            Description = "Construction of metal structures",
                            Name = "Construction of metal structures",
                            Pid = 33
                        },
                        new
                        {
                            ID = 35,
                            Description = "Houses and buildings",
                            Name = "Houses and buildings",
                            Pid = 33
                        },
                        new
                        {
                            ID = 36,
                            Description = "Metal products",
                            Name = "Metal products",
                            Pid = 33
                        },
                        new
                        {
                            ID = 37,
                            Description = "Metal works",
                            Name = "Metal works",
                            Pid = 33
                        },
                        new
                        {
                            ID = 38,
                            Description = "CNC-machining",
                            Name = "CNC-machining",
                            Pid = 37
                        },
                        new
                        {
                            ID = 39,
                            Description = "Forgings, Fasteners",
                            Name = "Forgings, Fasteners",
                            Pid = 37
                        },
                        new
                        {
                            ID = 40,
                            Description = "Gas, Plasma, Laser cutting",
                            Name = "Gas, Plasma, Laser cutting",
                            Pid = 37
                        },
                        new
                        {
                            ID = 41,
                            Description = "MIG, TIG, Aluminum welding",
                            Name = "MIG, TIG, Aluminum welding",
                            Pid = 37
                        },
                        new
                        {
                            ID = 42,
                            Description = "Plastic and Rubber",
                            Name = "Plastic and Rubber",
                            Pid = 1
                        },
                        new
                        {
                            ID = 43,
                            Description = "Packaging",
                            Name = "Packaging",
                            Pid = 42
                        },
                        new
                        {
                            ID = 44,
                            Description = "Plastic goods",
                            Name = "Plastic goods",
                            Pid = 42
                        },
                        new
                        {
                            ID = 45,
                            Description = "Plastic processing technology",
                            Name = "Plastic processing technology",
                            Pid = 42
                        },
                        new
                        {
                            ID = 46,
                            Description = "Blowing",
                            Name = "Blowing",
                            Pid = 45
                        },
                        new
                        {
                            ID = 47,
                            Description = "Moulding",
                            Name = "Moulding",
                            Pid = 45
                        },
                        new
                        {
                            ID = 48,
                            Description = "Plastics welding and processing",
                            Name = "Plastics welding and processing",
                            Pid = 45
                        },
                        new
                        {
                            ID = 49,
                            Description = "Plastic profiles",
                            Name = "Plastic profiles",
                            Pid = 42
                        },
                        new
                        {
                            ID = 50,
                            Description = "Printing",
                            Name = "Printing",
                            Pid = 1
                        },
                        new
                        {
                            ID = 51,
                            Description = "Advertising",
                            Name = "Advertising",
                            Pid = 50
                        },
                        new
                        {
                            ID = 52,
                            Description = "Book/Periodicals printing",
                            Name = "Book/Periodicals printing",
                            Pid = 50
                        },
                        new
                        {
                            ID = 53,
                            Description = "Labelling and packaging printing",
                            Name = "Labelling and packaging printing",
                            Pid = 50
                        },
                        new
                        {
                            ID = 54,
                            Description = "Textile and Clothing",
                            Name = "Textile and Clothing",
                            Pid = 1
                        },
                        new
                        {
                            ID = 55,
                            Description = "Clothing",
                            Name = "Clothing",
                            Pid = 54
                        },
                        new
                        {
                            ID = 56,
                            Description = "Textile",
                            Name = "Textile",
                            Pid = 54
                        },
                        new
                        {
                            ID = 57,
                            Description = "Wood",
                            Name = "Wood",
                            Pid = 1
                        },
                        new
                        {
                            ID = 58,
                            Description = "Other (Wood)",
                            Name = "Other (Wood)",
                            Pid = 57
                        },
                        new
                        {
                            ID = 59,
                            Description = "Wooden building materials",
                            Name = "Wooden building materials",
                            Pid = 57
                        },
                        new
                        {
                            ID = 60,
                            Description = "Wooden houses",
                            Name = "Wooden houses",
                            Pid = 57
                        },
                        new
                        {
                            ID = 61,
                            Description = "Other",
                            Name = "Other"
                        },
                        new
                        {
                            ID = 62,
                            Description = "Creative industries",
                            Name = "Creative industries",
                            Pid = 61
                        },
                        new
                        {
                            ID = 63,
                            Description = "Energy technology",
                            Name = "Energy technology",
                            Pid = 61
                        },
                        new
                        {
                            ID = 64,
                            Description = "Environment",
                            Name = "Environment",
                            Pid = 61
                        },
                        new
                        {
                            ID = 65,
                            Description = "Service",
                            Name = "Service"
                        },
                        new
                        {
                            ID = 66,
                            Description = "Business services",
                            Name = "Business services",
                            Pid = 65
                        },
                        new
                        {
                            ID = 67,
                            Description = "Engineering",
                            Name = "Engineering",
                            Pid = 65
                        },
                        new
                        {
                            ID = 68,
                            Description = "Information Technology and Telecommunications",
                            Name = "Information Technology and Telecommunications",
                            Pid = 65
                        },
                        new
                        {
                            ID = 69,
                            Description = "Data processing, Web portals, E-marketing",
                            Name = "Data processing, Web portals, E-marketing",
                            Pid = 68
                        },
                        new
                        {
                            ID = 70,
                            Description = "Programming, Consultancy",
                            Name = "Programming, Consultancy",
                            Pid = 68
                        },
                        new
                        {
                            ID = 71,
                            Description = "Software, Hardware",
                            Name = "Software, Hardware",
                            Pid = 68
                        },
                        new
                        {
                            ID = 72,
                            Description = "Telecommunications",
                            Name = "Telecommunications",
                            Pid = 68
                        },
                        new
                        {
                            ID = 73,
                            Description = "Tourism",
                            Name = "Tourism",
                            Pid = 65
                        },
                        new
                        {
                            ID = 74,
                            Description = "Translation services",
                            Name = "Translation services",
                            Pid = 65
                        },
                        new
                        {
                            ID = 75,
                            Description = "Transport and Logistics",
                            Name = "Transport and Logistics",
                            Pid = 65
                        },
                        new
                        {
                            ID = 76,
                            Description = "Air",
                            Name = "Air",
                            Pid = 75
                        },
                        new
                        {
                            ID = 77,
                            Description = "Rail",
                            Name = "Rail",
                            Pid = 75
                        },
                        new
                        {
                            ID = 78,
                            Description = "Road",
                            Name = "Road",
                            Pid = 75
                        },
                        new
                        {
                            ID = 79,
                            Description = "Water",
                            Name = "Water",
                            Pid = 75
                        });
                });

            modelBuilder.Entity("HelmesWebAPI.Entities.UserInfo", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAgreeToTerms")
                        .HasColumnType("bit");

                    b.Property<string>("SectorsIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("UserInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
